// This file is automatically generated. Do not edit it directly.
import "client-only";
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL || "https://tvzwqvemcspqxzqjizxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2endxdmVtY3NwcXh6cWppenhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg3Mjk1NjMsImV4cCI6MjA5NDMwNTU2M30.TNy0KmWmYTaH0egzSDWOAD-vkcStS5ybanUmSDnbZZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});
